### PR TITLE
Repartition matrix table to 10 partitions

### PR DESCRIPTION
**Pull request by KatalinaBobowik**
In order to save space, I've repartitioned the final matrix table to 10 partitions.

### CODE REVIEW

**Comment by KatalinaBobowik** [comment]
It would be neat to find a way to do this that's not hardcoded.

**Review by lgruen — APPROVED** [review]
> In order to save space, I've repartitioned the final matrix table to 10 partitions.

This isn't so much about space savings, but reducing the computational overhead incurred by having tiny partitions.

> It would be neat to find a way to do this that's not hardcoded.

You could make it dependent on the number of rows in the table.

**Comment by vladsaveliev** [comment]
Note that there is an issue with partitioning in Hail https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/repartition.20issue
Might not affect you though :)

**Comment by KatalinaBobowik** [comment]
> Note that there is an issue with partitioning in Hail https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/repartition.20issue
> Might not affect you though :)

That's really useful, thanks Vlad! I'll test it out first to see if it works ok 🤞

**Pull request merged**
